{{- if and .Values.notary.enabled (not .Values.notary.secretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "harbor.notary-server" . }}
  labels:
{{ include "harbor.labels" . | indent 4 }}
    component: notary
type: Opaque
data:
  {{- $ca := genCA "harbor-notary-ca" 365 }}
  {{- $cert := genSignedCert (include "harbor.notary-signer" .) nil nil 365 $ca }}
  tls.ca: {{ $ca.Cert | b64enc | quote }}
  tls.crt: {{ $cert.Cert | b64enc | quote }}
  tls.key: {{ $cert.Key | b64enc | quote }}
{{- end }}
