{{ if .Values.notary.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "harbor.notary-server" . }}
  labels:
{{ include "harbor.labels" . | indent 4 }}
    component: notary
data:
  server-config.postgres.json: |
    {
      "server": {
        "http_addr": ":4443"
      },
      "trust_service": {
        "type": "remote",
        "hostname": "{{ template "harbor.notary-signer" . }}",
        "port": "7899",
        "tls_ca_file": "/etc/ssl/notary/tls.ca",
        "key_algorithm": "ecdsa"
      },
      "logging": {
        "level": "{{ .Values.logLevel }}"
      },
      "storage": {
        "backend": "postgres",
        "db_url": "{{ template "harbor.database.notaryServer" . }}"
      },
      "auth": {
          "type": "token",
          "options": {
              "realm": "{{ .Values.externalURL }}/service/token",
              "service": "harbor-notary",
              "issuer": "harbor-token-issuer",
              "rootcertbundle": "/root.crt"
          }
      }
    }
  signer-config.postgres.json: |
    {
      "server": {
        "grpc_addr": ":7899",
        "tls_cert_file": "/etc/ssl/notary/tls.crt",
        "tls_key_file": "/etc/ssl/notary/tls.key"
      },
      "logging": {
        "level": "{{ .Values.logLevel }}"
      },
      "storage": {
        "backend": "postgres",
        "db_url": "{{ template "harbor.database.notarySigner" . }}",
        "default_alias": "defaultalias"
      }
    }
{{ end }}
